# Generated by:
#  genmakefile -m make --release src/cache.c src/dns.c src/gai_strerror.c src/getopt1.c src/getopt.c src/http.c src/init.c src/jconfig.c src/jwhois.c src/lookup.c src/regex.c src/rwhois.c src/string.c src/utils.c src/whois.c -o Makefile
CPPFLAGS = -Iinclude -DHAVE_MEMCPY -DHAVE_STRCASECMP -DHAVE_STRNCASECMP -DNOCACHE -DHAVE_ALLOCA_H -DHAVE_GAI_STRERROR -DHAVE_GETADDRINFO -DHAVE_GETOPT_LONG -DHAVE_ICONV -DHAVE_INET_ATON -DHAVE_INET_PTON_IPV6 -DHAVE_INTTYPES_H -DHAVE_LOCALE_H -DHAVE_MALLOC_H -DHAVE_NETDB_H -DHAVE_NETINET_IN_H -DHAVE_REGEXEC -DHAVE_STDINT_H -DHAVE_STRCASECMP -DHAVE_STRING_H -DHAVE_STRNCASECMP -DHAVE_STRTOL -DHAVE_SYS_FCNTL_H -DHAVE_SYS_SOCKET_H -DHAVE_SYS_STAT_H -DHAVE_SYS_TIME_H -DHAVE_SYS_TYPES_H -DSTDC_HEADERS -DPACKAGE=\"jwhois\" -DVERSION=\"1.0\" -DSYSCONFDIR=\"/etc\" -DWHOISSERVERS=\"whois-servers.net\" -DDEFAULTHOST=\"whois.internic.net\"


.PHONY: all
all: jwhois

VPATH = src

.c.o:
	$(CC) $(CFLAGS) $(EXTRA_CFLAGS) $(CPPFLAGS) $(DEFS) -c -o $@ $<


jwhois: \
  cache.o \
  dns.o \
  gai_strerror.o \
  http.o \
  init.o \
  jconfig.o \
  lookup.o \
  regex.o \
  rwhois.o \
  string.o \
  utils.o \
  whois.o \
  getopt.o \
  jwhois.o
	$(CC) $(CFLAGS) $(EXTRA_CFLAGS) $(LDFLAGS) $(EXTRA_LDFLAGS) -o $@ $^ $(LIBS) $(EXTRA_LIBS) $(STDC_LIBS)

clean:
	$(RM) *.o
	$(RM) getopt

